### POST request to create a user
POST http://localhost:3000/api/v1/user
Content-Type: application/json

{
  "display_name": "flind_",
  "email": "example@example.com",
  "password": "Password"
}


### DELETE request to delete a namespace
DELETE http://localhost:3000/api/v1/kube/namespace/spoutmc

### PATCH request to reset kube
PATCH http://localhost:3000/api/v1/kube/reset/spoutmc

### GET request to update replicas
GET http://localhost:3000/api/v1/kube/replicas/skyblock/1