apiVersion: spoutmc.io/v1alpha1
kind: SpoutServer
metadata:
  name: spoutproxy
spec:
  name: spoutproxy
  image: itzg/mc-proxy
  proxy: true
  restartPolicy:
    container:
      policy: always
    autoStartOnSpoutmcStart: true
  ports:
    - hostPort: "25565"
      containerPort: "25565"
    - hostPort: "4567"
      containerPort: "4567"
  env:
    TZ: Europe/Zurich
    TYPE: VELOCITY
    MAX_MEMORY: 1G
  volumes:
    - containerpath: "/server"
