apiVersion: v1
kind: ConfigMap
metadata:
  name: lobby-config
data:
  name: "lobby"
  image: "itzg/minecraft-server"
  lobby: "true"
  env.yaml: |-
    EULA: "TRUE"
    TYPE: "PAPER"
    ONLINE_MODE: "FALSE"
    ENFORCE_SECURE_PROFILE: "FALSE"
    MAX_MEMORY: "4G"
    VERSION: "1.20.4"
    GUI: "FALSE"
    CONSOLE: "FALSE"
    LOG_TIMESTAMP: "TRUE"
    TZ: "Europe/Zurich"
  volumes.yaml: |-
    - hostpath:
        - "testservers"
        - "data"
        - "spoutlobby"
      containerpath: "/data"
